In [14]:
import numpy as np
from math import gcd
import math 

            

tt = ['.#.####..#.#...#...##..#.#.##.',
      '..#####.##..#..##....#..#...#.',
      '......#.......##.##.#....##..#',
      '..#..##..#.###.....#.#..###.#.',
      '..#..#..##..#.#.##..###.......',
      '...##....#.##.#.#..##.##.#...#',
      '.##...#.#.##..#.#........#.#..',
      '.##...##.##..#.#.##.#.#.#.##.#',
      '#..##....#...###.#..##.#...##.',
      '.###.###..##......#..#...###.#',
      '.#..#.####.#..#....#.##..#.#.#',
      '..#...#..#.#######....###.....',
      '####..#.#.#...##...##....#..##',
      '##..#.##.#.#..##.###.#.##.##..',
      '..#.........#.#.#.#.......#..#',
      '...##.#.....#.#.##........#..#',
      '##..###.....#.............#.##',
      '.#...#....#..####.#.#......##.',
      '..#..##..###...#.....#...##..#',
      '...####..#.#.##..#....#.#.....',
      '####.#####.#.#....#.#....##.#.',
      '#.#..#......#.........##..#.#.',
      '#....##.....#........#..##.##.',
      '.###.##...##..#.##.#.#...#.#.#',
      '##.###....##....#.#.....#.###.',
      '..#...#......#........####..#.',
      '#....#.###.##.#...#.#.#.#.....',
      '.........##....#...#.....#..##',
      '###....#.........#..#..#.#.#..',
      '##...#...###.#..#.###....#.##.']

puzzle_input = tt

In [31]:

def str_to_int_map(ccc,DBG=True):
    
    yy = len(ccc[0])
    xx = len(ccc)
    if(DBG): print("xx,yy",xx,yy)

    map_int = np.zeros((xx,yy), dtype=int)
    
    for x in range(0,xx):
        for y in range(0,yy):
            if(DBG): print("x,y",x,y)

            if ccc[x][y]=='#':
                map_int[x][y]=1
            else:
                map_int[x][y]=0
            if(DBG): print("x,y,map_int[x][y]",x,y,map_int[x][y])

    return map_int

def count_asteroids(mmm,x0,y0,DBG=True):
    
    yy = len(mmm[0])
    xx = len(mmm)

    visible = np.full((xx,yy), -1)
    if(DBG): print(visible)

    for x in range(0,xx):
        for y in range(0,yy):
            if (x==x0) and (y==y0): continue
            if mmm[x][y]==0: continue
            if(DBG): print("x0,y0",x0,y0)
            if(DBG): print("x,y",x,y)
            dx = (x-x0)
            dy = (y-y0)
            pgcd = gcd(dx, dy)
            ddx = dx//pgcd
            ddy = dy//pgcd
            if(DBG): print("ddx,ddy",ddx,ddy)
            curx=x0+ddx
            cury=y0+ddy
            visible_flag=1
            if(DBG): print("curx,cury",curx,cury)
            while((curx>=0) and (curx<xx) and (cury>=0) and (cury<yy)):
                if ((mmm[curx][cury]==1) and (visible[curx][cury]!=0)):
                    visible[curx][cury]=visible_flag
                    visible_flag=0
                curx += ddx
                cury += ddy
                if(DBG): print("curx,cury",curx,cury)

    if(DBG): print(visible)
    count = np.count_nonzero(visible == 1)
    return count,visible

def remove(mmm, vvv):
    yy = len(mmm[0])
    xx = len(mmm)

    for x in range(0,xx):
        for y in range(0,yy):
            if vvv[x][y]==1:
                mmm[x][y]==0
    return mmm

def function(ccc, x0,y0,maxboom, DBG=True):

    yy = len(ccc[0])
    xx = len(ccc)

    mmm = str_to_int_map(ccc, DBG)
    if(DBG): print(mmm)

    boom = 0
    ast_left = mmm.copy()
    while(True):
        asteroids,visible = count_asteroids(ast_left,x0,y0,DBG)
        if (boom+asteroids>maxboom):
            if(DBG): print("boom, asteroids, maxboom",boom, asteroids, maxboom)
            break
        boom += asteroids
        if(DBG): print("boom",boom)
        if(DBG): print("ast_left",ast_left)
        if(DBG): print("visible",visible)
        ast_left = remove(ast_left,visible)
        if(DBG): print("ast_left_remove",ast_left)
    
    # rotate and count
    angles={}
    for x in range(0,xx):
        for y in range(0,yy):
            if(ast_left[x][y]==1):
                angle=-math.atan2(y-y0,x-x0)+math.pi/2
                angles[angle]=(x,y)

    if(DBG): 
        for key in sorted(angles):
            print("key,angles[key]",key,angles[key])
            
    for key in sorted(angles):
        boom += 1
        if (boom==maxboom):
            ret = [angles[key],boom]
            break
    
    if(DBG): print("ret",ret)

    return ret



In [32]:
def test(cc, x0,y0,maxboom,expected=None):
    result = str(function(cc,x0,y0,maxboom,True))
    flag = (result == expected)
    if (expected==None):
        print(str(cc) + " -> "+ str(result))
    else:
        print(str(cc) + " -> "+str(result), " -> "+ str(flag))

In [33]:
t1=['.#..#',
    '.....',
    '#####',
    '....#',
    '...##']

test(t1,4,3,3)# 

tt = ['......#.#.',
      '#..#.#....',
      '..#######.',
      '.#.#.###..',
      '.#..#.....',
      '..#....#.#',
      '#..#....#.',
      '.##.#..###',
      '##...#..#.',
      '.#....####']

#test(tt, 8,5,30)




tt = ['#.#...#.#.',
      '.###....#.',
      '.#....#...',
      '##.#.#.#.#',
      '....#.#.#.',
      '.##..###.#',
      '..#...##..',
      '..##....##',
      '......#...',
      '.####.###.']

#test(tt,2,1,20)


tt = ['.#..#..###',
      '####.###.#',
      '....###.#.',
      '..###.##.#',
      '##.##.#.#.',
      '....###..#',
      '..#.#..#.#',
      '#..#.#.###',
      '.##...##.#',
      '.....#.#..']

#test(tt,3,6,40)



tt = ['.#..##.###...#######',
      '##.############..##.',
      '.#.######.########.#',
      '.###.#######.####.#.',
      '#####.##.#.##.###.##',
      '..#####..#.#########',
      '####################',
      '#.####....###.#.#.##',
      '##.#################',
      '#####.##.###..####..',
      '..######..##.#######',
      '####.##.####...##..#',
      '.#####..#.######.###',
      '##...#.##########...',
      '#.##########.#######',
      '.####.#.###.###.#.##',
      '....##.##.###..#####',
      '.#.#.###########.###',
      '#.#.#.#####.####.###',
      '###.##.####.##.#..##']

test(tt, 13,11,200)






xx,yy 5 5
x,y 0 0
x,y,map_int[x][y] 0 0 0
x,y 0 1
x,y,map_int[x][y] 0 1 1
x,y 0 2
x,y,map_int[x][y] 0 2 0
x,y 0 3
x,y,map_int[x][y] 0 3 0
x,y 0 4
x,y,map_int[x][y] 0 4 1
x,y 1 0
x,y,map_int[x][y] 1 0 0
x,y 1 1
x,y,map_int[x][y] 1 1 0
x,y 1 2
x,y,map_int[x][y] 1 2 0
x,y 1 3
x,y,map_int[x][y] 1 3 0
x,y 1 4
x,y,map_int[x][y] 1 4 0
x,y 2 0
x,y,map_int[x][y] 2 0 1
x,y 2 1
x,y,map_int[x][y] 2 1 1
x,y 2 2
x,y,map_int[x][y] 2 2 1
x,y 2 3
x,y,map_int[x][y] 2 3 1
x,y 2 4
x,y,map_int[x][y] 2 4 1
x,y 3 0
x,y,map_int[x][y] 3 0 0
x,y 3 1
x,y,map_int[x][y] 3 1 0
x,y 3 2
x,y,map_int[x][y] 3 2 0
x,y 3 3
x,y,map_int[x][y] 3 3 0
x,y 3 4
x,y,map_int[x][y] 3 4 1
x,y 4 0
x,y,map_int[x][y] 4 0 0
x,y 4 1
x,y,map_int[x][y] 4 1 0
x,y 4 2
x,y,map_int[x][y] 4 2 0
x,y 4 3
x,y,map_int[x][y] 4 3 1
x,y 4 4
x,y,map_int[x][y] 4 4 1
[[0 1 0 0 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 1 1]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
x0,y0 4 3
x,y 0 1
ddx,ddy -2 -1
c

x,y,map_int[x][y] 9 7 1
x,y 9 8
x,y,map_int[x][y] 9 8 0
x,y 9 9
x,y,map_int[x][y] 9 9 1
x,y 9 10
x,y,map_int[x][y] 9 10 1
x,y 9 11
x,y,map_int[x][y] 9 11 1
x,y 9 12
x,y,map_int[x][y] 9 12 0
x,y 9 13
x,y,map_int[x][y] 9 13 0
x,y 9 14
x,y,map_int[x][y] 9 14 1
x,y 9 15
x,y,map_int[x][y] 9 15 1
x,y 9 16
x,y,map_int[x][y] 9 16 1
x,y 9 17
x,y,map_int[x][y] 9 17 1
x,y 9 18
x,y,map_int[x][y] 9 18 0
x,y 9 19
x,y,map_int[x][y] 9 19 0
x,y 10 0
x,y,map_int[x][y] 10 0 0
x,y 10 1
x,y,map_int[x][y] 10 1 0
x,y 10 2
x,y,map_int[x][y] 10 2 1
x,y 10 3
x,y,map_int[x][y] 10 3 1
x,y 10 4
x,y,map_int[x][y] 10 4 1
x,y 10 5
x,y,map_int[x][y] 10 5 1
x,y 10 6
x,y,map_int[x][y] 10 6 1
x,y 10 7
x,y,map_int[x][y] 10 7 1
x,y 10 8
x,y,map_int[x][y] 10 8 0
x,y 10 9
x,y,map_int[x][y] 10 9 0
x,y 10 10
x,y,map_int[x][y] 10 10 1
x,y 10 11
x,y,map_int[x][y] 10 11 1
x,y 10 12
x,y,map_int[x][y] 10 12 0
x,y 10 13
x,y,map_int[x][y] 10 13 1
x,y 10 14
x,y,map_int[x][y] 10 14 1
x,y 10 15
x,y,map_int[x][y] 10 15 1
x,y 10 16
x,y,ma

curx,cury -5 1
x0,y0 13 11
x,y 4 7
ddx,ddy -9 -4
curx,cury 4 7
curx,cury -5 3
x0,y0 13 11
x,y 4 9
ddx,ddy -9 -2
curx,cury 4 9
curx,cury -5 7
x0,y0 13 11
x,y 4 11
ddx,ddy -1 0
curx,cury 12 11
curx,cury 11 11
curx,cury 10 11
curx,cury 9 11
curx,cury 8 11
curx,cury 7 11
curx,cury 6 11
curx,cury 5 11
curx,cury 4 11
curx,cury 3 11
curx,cury 2 11
curx,cury 1 11
curx,cury 0 11
curx,cury -1 11
x0,y0 13 11
x,y 4 12
ddx,ddy -9 1
curx,cury 4 12
curx,cury -5 13
x0,y0 13 11
x,y 4 14
ddx,ddy -3 1
curx,cury 10 12
curx,cury 7 13
curx,cury 4 14
curx,cury 1 15
curx,cury -2 16
x0,y0 13 11
x,y 4 15
ddx,ddy -9 4
curx,cury 4 15
curx,cury -5 19
x0,y0 13 11
x,y 4 16
ddx,ddy -9 5
curx,cury 4 16
curx,cury -5 21
x0,y0 13 11
x,y 4 18
ddx,ddy -9 7
curx,cury 4 18
curx,cury -5 25
x0,y0 13 11
x,y 4 19
ddx,ddy -9 8
curx,cury 4 19
curx,cury -5 27
x0,y0 13 11
x,y 5 2
ddx,ddy -8 -9
curx,cury 5 2
curx,cury -3 -7
x0,y0 13 11
x,y 5 3
ddx,ddy -1 -1
curx,cury 12 10
curx,cury 11 9
curx,cury 10 8
curx,cury 9 7
curx,cury 8 6
cur

ddx,ddy -1 2
curx,cury 12 13
curx,cury 11 15
curx,cury 10 17
curx,cury 9 19
curx,cury 8 21
x0,y0 13 11
x,y 12 14
ddx,ddy -1 3
curx,cury 12 14
curx,cury 11 17
curx,cury 10 20
x0,y0 13 11
x,y 12 15
ddx,ddy -1 4
curx,cury 12 15
curx,cury 11 19
curx,cury 10 23
x0,y0 13 11
x,y 12 17
ddx,ddy -1 6
curx,cury 12 17
curx,cury 11 23
x0,y0 13 11
x,y 12 18
ddx,ddy -1 7
curx,cury 12 18
curx,cury 11 25
x0,y0 13 11
x,y 12 19
ddx,ddy -1 8
curx,cury 12 19
curx,cury 11 27
x0,y0 13 11
x,y 13 0
ddx,ddy 0 -1
curx,cury 13 10
curx,cury 13 9
curx,cury 13 8
curx,cury 13 7
curx,cury 13 6
curx,cury 13 5
curx,cury 13 4
curx,cury 13 3
curx,cury 13 2
curx,cury 13 1
curx,cury 13 0
curx,cury 13 -1
x0,y0 13 11
x,y 13 1
ddx,ddy 0 -1
curx,cury 13 10
curx,cury 13 9
curx,cury 13 8
curx,cury 13 7
curx,cury 13 6
curx,cury 13 5
curx,cury 13 4
curx,cury 13 3
curx,cury 13 2
curx,cury 13 1
curx,cury 13 0
curx,cury 13 -1
x0,y0 13 11
x,y 13 5
ddx,ddy 0 -1
curx,cury 13 10
curx,cury 13 9
curx,cury 13 8
curx,cury 13 7
curx,cury 13 6


ret [(2, 8), 200]
['.#..##.###...#######', '##.############..##.', '.#.######.########.#', '.###.#######.####.#.', '#####.##.#.##.###.##', '..#####..#.#########', '####################', '#.####....###.#.#.##', '##.#################', '#####.##.###..####..', '..######..##.#######', '####.##.####...##..#', '.#####..#.######.###', '##...#.##########...', '#.##########.#######', '.####.#.###.###.#.##', '....##.##.###..#####', '.#.#.###########.###', '#.#.#.#####.####.###', '###.##.####.##.#..##'] -> [(2, 8), 200]


In [35]:
function(puzzle_input,25, 22,200,False)

[(4, 5), 200]